### ISSUE TITLE
FATAL EXCEPTION in the system (not in my application)

### ISSUE THREAD

**Issue by dutpas** [dutpas/HG#2]
I don't know why I have this error, whereas there is no activity of my cyclic application (110 ms) when that occurs 

In the trace, "+++++++++" means the end of its cyclic processing is at this time: 654945 ms.

It seems to be a cache problem in javafx.scene.Parent (TBC).

Note: 654945 ms = 11 mn of active game 

An idea?

--------------------

I/System.out(17724): trace tExec - heure : 654945 ms --- onPoursuitOuPas  / tExec: 1

I/System.out(17724): heure : 654945 ms --- Fin traitementCyclique standard - taille liste des VA 1 / taille liste des VE: 4 / dureeTraittCPUdsUneBDTms: 214

I/System.out(17724): trace tExec - heure : 654945 ms --- SUPER IMPORTANT - Duree du traitementCyclique :  / tExec: 15

I/System.out(17724): trace CPU - heure : 654945 ms --- tExec: Phase no 4 / dureeTraittCPUdsUneBDTms MAX ds la phase : 214

I/System.out(17724): heure : 654945 ms --- Phase no 4 / dureeTraittCPUdsUneBDTms MAX ds la phase : 214

I/System.out(17724): heure : 654945 ms --- Fin traitementCyclique  / bBDTactive: true / bBDTpause: false

I/System.out(17724): heure : 654945 ms --- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioTrackShared(  316): front(0x5b6d), mIsOut(1), mAvailToClient=1 stepCount=1114 minimum=1486

D/AudioTrackShared(  316): front(0x60800), mIsOut(1), mAvailToClient=1024 stepCount=1024 minimum=2048, FUTEX_WAKE

D/AudioTrackShared(  316): front(0x60800), mIsOut 1, avail 2048, mFrameCount 4096, filled 2048

V/AudioTrack(  316): obtainBuffer(2048) returned 2048 = 2048 + 0 err 0

D/AudioTrackShared(  316): front(0x60800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/AudioTrackShared(  316): front(0x60800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/AudioTrackShared(  316): front(0x60800), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/AudioTrackShared(  316): front(0x687d), mIsOut(1), mAvailToClient=372 stepCount=1115 minimum=1486, FUTEX_WAKE

D/AudioTrackShared(  316): front(0x8fac), mIsOut(1), mAvailToClient=1 stepCount=1115 minimum=1486

E/AndroidRuntime(17724): FATAL EXCEPTION: JavaFX Application Thread

E/AndroidRuntime(17724): Process: com.gluonapplication, PID: 17724

E/AndroidRuntime(17724): java.lang.ArrayIndexOutOfBoundsException: length=30; index=-1

E/AndroidRuntime(17724): 	at java.util.ArrayList.get(ArrayList.java:310)

E/AndroidRuntime(17724): 	at javafx.scene.Parent.updateCachedBounds(Parent.java:1583)

E/AndroidRuntime(17724): 	at javafx.scene.Parent.recomputeBounds(Parent.java:1527)

E/AndroidRuntime(17724): 	at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1380)

E/AndroidRuntime(17724): 	at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078)

E/AndroidRuntime(17724): 	at javafx.scene.Node.updateGeomBounds(Node.java:3577)

E/AndroidRuntime(17724): 	at javafx.scene.Node.getGeomBounds(Node.java:3530)

E/AndroidRuntime(17724): 	at javafx.scene.Node.getLocalBounds(Node.java:3478)

E/AndroidRuntime(17724): 	at javafx.scene.Node.impl_intersectsBounds(Node.java:5013)

E/AndroidRuntime(17724): 	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2931)

E/AndroidRuntime(17724): 	at javafx.scene.Node.impl_pickNode(Node.java:4912)

E/AndroidRuntime(17724): 	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3903)

E/AndroidRuntime(17724): 	at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3489)

E/AndroidRuntime(17724): 	at javafx.scene.Scene.pick(Scene.java:1946)

E/AndroidRuntime(17724): 	at javafx.scene.Scene.pick(Scene.java:1921)

E/AndroidRuntime(17724): 	at javafx.scene.Scene.access$4900(Scene.java:159)

E/AndroidRuntime(17724): 	at javafx.scene.Scene$ScenePeerListener.scrollEvent(Scene.java:2584)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.ScrollGestureRecognizer.lambda$sendScrollEvent$427(ScrollGestureRecognizer.java:303)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.ScrollGestureRecognizer.access$lambda$3(ScrollGestureRecognizer.java)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.ScrollGestureRecognizer$$Lambda$4.run(Unknown Source)

E/AndroidRuntime(17724): 	at java.security.AccessController.doPrivileged(AccessController.java:52)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.ScrollGestureRecognizer.sendScrollEvent(ScrollGestureRecognizer.java:301)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.ScrollGestureRecognizer.lambda$new$424(ScrollGestureRecognizer.java:118)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.ScrollGestureRecognizer.access$lambda$0(ScrollGestureRecognizer.java)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.ScrollGestureRecognizer$$Lambda$1.invalidated(Unknown Source)

E/AndroidRuntime(17724): 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)

E/AndroidRuntime(17724): 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)

E/AndroidRuntime(17724): 	at javafx.beans.property.DoublePropertyBase.fireValueChangedEvent(DoublePropertyBase.java:106)

E/AndroidRuntime(17724): 	at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)

E/AndroidRuntime(17724): 	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:147)

E/AndroidRuntime(17724): 	at com.sun.scenario.animation.shared.InterpolationInterval$DoubleInterpolationInterval.interpolate(InterpolationInterval.java:263)

E/AndroidRuntime(17724): 	at com.sun.scenario.animation.shared.SimpleClipInterpolator.interpolate(SimpleClipInterpolator.java:137)

E/AndroidRuntime(17724): 	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:209)

E/AndroidRuntime(17724): 	at javafx.animation.Timeline.impl_playTo(Timeline.java:176)

E/AndroidRuntime(17724): 	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)

E/AndroidRuntime(17724): 	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:99)

E/AndroidRuntime(17724): 	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)

E/AndroidRuntime(17724): 	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)

E/AndroidRuntime(17724): 	at javafx.animation.Animation$1.access$lambda$0(Animation.java)

E/AndroidRuntime(17724): 	at javafx.animation.Animation$1$$Lambda$1.run(Unknown Source)

E/AndroidRuntime(17724): 	at java.security.AccessController.doPrivileged(AccessController.java:52)

E/AndroidRuntime(17724): 	at javafx.animation.Animation$1.timePulse(Animation.java:185)

E/AndroidRuntime(17724): 	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)

E/AndroidRuntime(17724): 	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:521)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:503)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$387(QuantumToolkit.java:321)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.QuantumToolkit.access$lambda$2(QuantumToolkit.java)

E/AndroidRuntime(17724): 	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$3.run(Unknown Source)

E/AndroidRuntime(17724): 	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)

E/AndroidRuntime(17724): 	at com.sun.glass.ui.monocle.RunnableProcesso

D/AudioTrackShared(  316): front(0x14000), mIsOut(1), mAvailToClient=0 stepCount=558 minimum=1486

D/AudioTrackShared(  316): front(0x1422d), mIsOut(1), mAvailToClient=558 stepCount=557 minimum=1486

D/QMCX983D(  405): waitting for enable m or o sensor

D/QMCX983D(  405): QMC_IOCTL_GET_OPEN_STATUS failed

D/QMCX983D(  405): QMC_IOCTL_GET_DELAY failed

D/QMCX983D(  405): QMC_IOCTL_SET_YPR failed!

D/SettingsProvider(  842): lookupValue table global cache.fullyMatchesDisk() dropbox:data_app_crash

D/AudioTrackShared(  316): front(0x8fac), mIsOut(1), mAvailToClient=1 stepCount=1115 minimum=1486

D/AudioTrackShared(  316): front(0x687d), mIsOut 1, avail 1487, mFrameCount 4458, filled 2971

V/AudioTrack(  316): obtainBuffer(1486) returned 1487 = 1486 + 1 err 0

D/SettingsProvider(  842): lookupValue table global cache contains Key send_action_app_error , value = Bundle[{value=1}]

D/AudioTrackShared(  316): front(0x687d), mIsOut 1, avail 1, mFrameCount 4458, filled 4457

V/AudioTrack(  316): obtainBuffer(1486) returned 1 = 1 + 0 err 0

D/AudioTrackShared(  316): front(0x2a0c00), mIsOut(1), mAvailToClient=0 stepCount=1024 minimum=2048

D/AudioTrackShared(  316): front(0x6f5c00), mIsOut(1), mAvailToClient=0 stepCount=1024 minimum=2048

D/AudioTrackShared(  316): front(0x942c00), mIsOut(1), mAvailToClient=0 stepCount=1024 minimum=2048

D/AudioTrackShared(  316): front(0xce2800), mIsOut(1), mAvailToClient=1024 stepCount=1024 minimum=2048, FUTEX_WAKE

D/AudioTrackShared(  316): front(0x19c3c00), mIsOut(1), mAvailToClient=1024 stepCount=1024 minimum=2048, FUTEX_WAKE

D/AudioTrackShared(  316): front(0xce2800), mIsOut 1, avail 2048, mFrameCount 4096, filled 2048

D/PowerManagerService(  842): acquireWakeLockInternal: lock=844210852, flags=0x1, tag="ActivityManager-Launch", ws=null, uid=1000, pid=842

V/AudioTrack(  316): obtainBuffer(2048) returned 2048 = 2048 + 0 err 0

D/PowerManagerService(  842): updateWakeLockSummaryLocked: mWakefulness=Awake, mWakeLockSummary=0x1

D/AudioTrackShared(  316): front(0x19c3c00), mIsOut 1, avail 2048, mFrameCount 4096, filled 2048

D/PowerManagerService(  842): updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=11762053 (in 112003 ms)

D/AudioTrackShared(  316): front(0x14c0800), mIsOut(1), mAvailToClient=1024 stepCount=1024 minimum=2048, FUTEX_WAKE

D/PowerManagerService(  842): mDisplayPowerRequest.policy = 3

V/AudioTrack(  316): obtainBuffer(2048) returned 2048 = 2048 + 0 err 0

D/WifiDisplayAdapter(  842): getWifiDisplayStatusLocked: result=WifiDisplayStatus{featureState=2, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}

D/AudioTrackShared(  316): front(0x19c3c00), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/PowerManagerService(  842): isWfdEnabled() mWfdStatus=WifiDisplayStatus{featureState=2, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}, return false

D/AudioTrackShared(  316): front(0x12d3c00), mIsOut(1), mAvailToClient=1024 stepCount=1024 minimum=2048, FUTEX_WAKE

D/DisplayPowerController(  842): requestPowerState: policy=BRIGHT, useProximitySensor=false, screenBrightness=200, screenAutoBrightnessAdjustment=-0.98, useAutoBrightness=true, blockScreenOn=false, lowPowerMode=false, boostScreenBrightness=false, dozeScreenBrightness=-1, dozeScreenState=UNKNOWN, waitForNegativeProximity=false

D/AudioTrackShared(  316): front(0xce2800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

I/PowerManagerService(  842): setBrightness mButtonLight 0.

D/AudioTrackShared(  316): front(0x19c3c00), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/PowerManagerService(  842): updateDisplayPowerStateLocked: mDisplayReady=true, policy=3, mWakefulness=1, mWakeLockSummary=0x1, mUserActivitySummary=0x1, mBootCompleted=true, mScreenBrightnessBoostInProgress=false

D/AudioTrackShared(  316): front(0x14c0800), mIsOut 1, avail 2048, mFrameCount 4096, filled 2048

D/ActivityThread(17724): ACT-AM_ON_PAUSE_CALLED ActivityRecord{4c4284b token=android.os.BinderProxy@ce3228 {com.gluonapplication/javafxports.android.FXActivity}}

V/AudioTrack(  316): obtainBuffer(2048) returned 2048 = 2048 + 0 err 0

D/PowerManagerNotifier(  842): onWakeLockAcquired: flags=1, tag="ActivityManager-Launch", packageName=android, ownerUid=1000, ownerPid=842, workSource=null

D/AudioTrackShared(  316): front(0x19c3c00), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/AudioTrackShared(  316): front(0xce2800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/AudioTrackShared(  316): front(0x1b4b400), mIsOut(1), mAvailToClient=0 stepCount=1024 minimum=2048

D/AudioTrackShared(  316): front(0xce2800), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/AudioTrackShared(  316): front(0x14c0800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/AudioTrackShared(  316): front(0x12d3c00), mIsOut 1, avail 2048, mFrameCount 4096, filled 2048

V/AudioTrack(  316): obtainBuffer(2048) returned 2048 = 2048 + 0 err 0

D/AudioTrackShared(  316): front(0x14c0800), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/AudioTrackShared(  316): front(0x14c0800), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/AudioTrackShared(  316): front(0x12d3c00), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/AudioTrackShared(  316): front(0x12d3c00), mIsOut 1, avail 0, mFrameCount 4096, filled 4096

D/AudioTrackShared(  316): front(0x12d3c00), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/SettingsProvider(  842): lookupValue table global cache.fullyMatchesDisk() logcat_for_data_app_crash

V/SettingsInterface(  842):  from settings cache , name = dropbox:data_app_crash , value = null

D/FeatureProxyBase(  842): FeatureProxyBase class constructor

V/SettingsInterface(  842):  from settings cache , name = dropbox:data_app_crash , value = null

V/SettingsInterface(  842):  from settings cache , name = dropbox_age_seconds , value = null

V/SettingsInterface(  842):  from settings cache , name = dropbox_max_files , value = null

D/MultiWindow(  842): MultiWindowProxy constructor.

D/FeatureProxyBase(  842): getService(), serviceName = multiwindow_service_v1

V/SettingsInterface(  842):  from settings cache , name = dropbox_quota_percent , value = null

V/SettingsInterface(  842):  from settings cache , name = dropbox_reserve_percent , value = null

V/SettingsInterface(  842):  from settings cache , name = dropbox_quota_kb , value = null

D/FeatureProxyBase(  842): FeatureProxyBase class constructor

D/MultiWindow(  842): MultiWindowProxy constructor.

D/FeatureProxyBase(  842): getService(), serviceName = multiwindow_service_v1

I/BufferQueue(  842): [unnamed-842-16](this:0x7f970ea000,id:16,api:0,p:-1,c:-1) BufferQueue core=(842:system_server)

I/BufferQueueConsumer(  842): [unnamed-842-16](this:0x7f970ea000,id:16,api:0,p:-1,c:842) connect(C): consumer=(842:system_server) controlledByApp=false

I/BufferQueueConsumer(  842): [unnamed-842-16](this:0x7f970ea000,id:16,api:0,p:-1,c:842) setConsumerName: unnamed-842-16

I/BufferQueueConsumer(  842): [ScreenshotClient](this:0x7f970ea000,id:16,api:0,p:-1,c:842) setConsumerName: ScreenshotClient

D/Surface (  287): Surface::connect(this=0x7f95df6c00,api=1)

I/BufferQueueProducer(  842): [ScreenshotClient](this:0x7f970ea000,id:16,api:1,p:287,c:842) connect(P): api=1 producer=(287:/system/bin/surfaceflinger) producerControlledByApp=false

D/Surface (  287): Surface::setBuffersDimensions(this=0x7f95df6c00,w=336,h=336)

I/BufferQueueProducer(  842): [ScreenshotClient](this:0x7f970ea000,id:16,api:1,p:287,c:842) new GraphicBuffer needed

I/[MALI][Gralloc](  287): Usage: 0x333, format: 0x1 stride: 336 vertical_stride: 336 size: 451584

D/AudioTrackShared(  316): front(0x5b6d), mIsOut 1, avail 1115, mFrameCount 4458, filled 3343

V/AudioTrack(  316): obtainBuffer(1486) returned 1115 = 1115 + 0 err 0

D/GraphicBuffer(  287): alloc, handle(0x7f95412d40) (w:336 h:336 s:336 f:0x1 u:0x000333) err(0)

D/AudioTrackShared(  316): front(0x5b6d), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

V/AudioTrack(  316): obtainBuffer(371) returned 0 = 0 + 0 err -11

D/AudioTrackShared(  316): front(0x5b6d), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

D/AudioTrackShared(  316): front(0x5b6d), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

D/AudioTrackShared(  316): front(0x5b6d), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/GraphicBuffer(  842): register, handle(0x7f90294b00) (w:336 h:336 s:336 f:0x1 u:0x000333)

D/GraphicBuffer(  287): free, handle(0x7f95412d40) (w:336 h:336 s:336 f:0x1 u:0x000333)

D/GraphicBuffer(  287): register, handle(0x7f8ebe0560) (w:336 h:336 s:336 f:0x1 u:0x000333)

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 1116, mFrameCount 4458, filled 3342

V/AudioTrack(  316): obtainBuffer(1486) returned 1116 = 838 + 278 err 0

D/ActivityThread(17724): ACT-PAUSE_ACTIVITY_FINISHING handled : 0 / android.os.BinderProxy@ce3228

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 278, mFrameCount 4458, filled 4180

V/AudioTrack(  316): obtainBuffer(648) returned 278 = 278 + 0 err 0

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

V/AudioTrack(  316): obtainBuffer(370) returned 0 = 0 + 0 err -11

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 1116, mFrameCount 4458, filled 3342

V/AudioTrack(  316): obtainBuffer(1486) returned 1116 = 838 + 278 err 0

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 278, mFrameCount 4458, filled 4180

V/AudioTrack(  316): obtainBuffer(648) returned 278 = 278 + 0 err 0

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

V/AudioTrack(  316): obtainBuffer(370) returned 0 = 0 + 0 err -11

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, avail 0, mFrameCount 4458, filled 4458

D/AudioTrackShared(  316): front(0x8fac), mIsOut 1, obtainBuffer() FUTEX_WAIT

D/Surface (  287): Surface::disconnect(this=0x7f95df6c00,api=1)

D/GraphicBuffer(  287): unregister, handle(0x7f8ebe0560) (w:336 h:336 s:336 f:0x1 u:0x000333)

I/BufferQueueProducer(  842): [ScreenshotClient](this:0x7f970ea000,id:16,api:1,p:-1,c:842) disconnect(P): api 1

I/BufferQueueConsumer(  842): [ScreenshotClient](this:0x7f970ea000,id:16,api:1,p:-1,c:842) getReleasedBuffers: returning mask 0xffffffffffffffff

I/art     (  842): [heap] RegisterNativeAllocation start bytes:451584

I/art     (  842): [heap] RegisterNativeAllocation RunFinalization time 1

I/art     (  842): [heap] RunFinalization start

I/art     (  842): [heap] RunFinalization end

I/art     (  842): [heap] RegisterNativeAllocation native_bytes_allocated_:0

I/art     (  842): [heap] RegisterNativeAllocation new_native_bytes_allocated:0, native_bytes_allocated_:451584, native_footprint_gc_watermark_:524288, growth_limit_:268435456

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

I/BufferQueueConsumer(  842): [ScreenshotClient](this:0x7f970ea000,id:16,api:1,p:-1,c:-1) disconnect(C)

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/AudioFlinger_Threads(  316): before set Effect volume vlf 0.000000, vr 0.000000,  vaf 0.000000

D/AudioFlinger_Threads(  316): set mixer volume vlf 0.000000, vrf 0.000000, vaf 0.000000

D/GraphicBuffer(  842): unregister, handle(0x7f90294b00) (w:336 h:336 s:336 f:0x1 u:0x000333)

**Comment by dutpas** [comment]
The problem was about the MediaPlayer user in a real time context: preparing an audio file and starting take a lot of time (from 50 to 100 ms) . And, when several songs are prepared almost at the same time, the real time explodes. Solution: prepare a single song then another one
